apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: webapp

resources:
- namespace.yaml
- priority-class.yaml
- service-account.yaml
- rbac.yaml
- configmap.yaml
- secret.yaml
- limit-range.yaml
- resource-quota.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
- hpa.yaml
- vpa.yaml
- pdb.yaml
- network-policy.yaml

commonLabels:
  app: webapp
  environment: production
  version: v1

commonAnnotations:
  managed-by: kustomize