apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: webapp
  labels:
    app: webapp
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
spec:
  type: ClusterIP

  selector:
    app: webapp
  
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  
  sessionAffinity: None